"""Init

Revision ID: 6d0489f26760
Revises: 
Create Date: 2025-05-14 09:22:03.812952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0489f26760'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('id_')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id_', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_'),
    sa.UniqueConstraint('id_'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity_tags',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id_'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id_'], onupdate='CASCADE', ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_tags')
    op.drop_table('tags')
    op.drop_table('activities')
    # ### end Alembic commands ###
